export const DUMMY_INTERACTIONS = [
  {
    id: 'e1',
    projectId: 'Quantum Dynamics',
    text: 'Project kickoff meeting held',
    createdAt: 1672531200000,
    type: 'Event',
    message: 'Project kickoff meeting held',
  },
  {
    id: 'e2',
    projectId: 'Nexus Technologies',
    text: 'Major milestone achieved',
    createdAt: 1675209600000,
    type: 'Event',
    message: 'Major milestone achieved',
  },
  {
    id: 'e3',
    projectId: 'Emerald Innovations',
    text: 'Client presentation scheduled',
    createdAt: 1677888000000,
    type: 'Event',
    message: 'Client presentation scheduled',
  },
  {
    id: 'e4',
    projectId: 'Stellar Systems',
    text: 'Team restructuring announced',
    createdAt: 1680566400000,
    type: 'Event',
    message: 'Team restructuring announced',
  },
  {
    id: 'e5',
    projectId: 'Apex Solutions',
    text: 'Budget review completed',
    createdAt: 1683158400000,
    type: 'Event',
    message: 'Budget review completed',
  },
  {
    id: 'e6',
    projectId: 'Fusion Enterprises',
    text: 'New team member onboarded',
    createdAt: 1685836800000,
    type: 'Event',
    message: 'New team member onboarded',
  },
  {
    id: 'e7',
    projectId: 'Zenith Corporation',
    text: 'Project deadline extended',
    createdAt: 1688515200000,
    type: 'Event',
    message: 'Project deadline extended',
  },
  {
    id: 'e8',
    projectId: 'Prism Industries',
    text: 'Unexpected issue encountered',
    createdAt: 1691193600000,
    type: 'Event',
    message: 'Unexpected issue encountered',
  },
  {
    id: 'e9',
    projectId: 'Velocity Ventures',
    text: 'Critical bug resolved',
    createdAt: 1693872000000,
    type: 'Event',
    message: 'Critical bug resolved',
  },
  {
    id: 'e10',
    projectId: 'Oasis Innovations',
    text: 'Client feedback received',
    createdAt: 1696550400000,
    type: 'Event',
    message: 'Client feedback received',
  },
  {
    id: 'e11',
    projectId: 'Horizon Dynamics',
    text: 'Project kickoff meeting held',
    createdAt: 1699228800000,
    type: 'Event',
    message: 'Project kickoff meeting held',
  },
  {
    id: 'e12',
    projectId: 'Catalyst Systems',
    text: 'Major milestone achieved',
    createdAt: 1701820800000,
    type: 'Event',
    message: 'Major milestone achieved',
  },
  {
    id: 'e13',
    projectId: 'Nova Technologies',
    text: 'Client presentation scheduled',
    createdAt: 1704499200000,
    type: 'Event',
    message: 'Client presentation scheduled',
  },
  {
    id: 'e14',
    projectId: 'Aegis Solutions',
    text: 'Team restructuring announced',
    createdAt: 1673136000000,
    type: 'Event',
    message: 'Team restructuring announced',
  },
  {
    id: 'e15',
    projectId: 'Phoenix Enterprises',
    text: 'Budget review completed',
    createdAt: 1675814400000,
    type: 'Event',
    message: 'Budget review completed',
  },
  {
    id: 'e16',
    projectId: 'Pinnacle Industries',
    text: 'New team member onboarded',
    createdAt: 1678492800000,
    type: 'Event',
    message: 'New team member onboarded',
  },
  {
    id: 'e17',
    projectId: 'Vortex Innovations',
    text: 'Project deadline extended',
    createdAt: 1681171200000,
    type: 'Event',
    message: 'Project deadline extended',
  },
  {
    id: 'e18',
    projectId: 'Meridian Systems',
    text: 'Unexpected issue encountered',
    createdAt: 1683849600000,
    type: 'Event',
    message: 'Unexpected issue encountered',
  },
  {
    id: 'e19',
    projectId: 'Cyber Dynamics',
    text: 'Critical bug resolved',
    createdAt: 1686528000000,
    type: 'Event',
    message: 'Critical bug resolved',
  },
  {
    id: 'e20',
    projectId: 'Elysium Technologies',
    text: 'Client feedback received',
    createdAt: 1689206400000,
    type: 'Event',
    message: 'Client feedback received',
  },
  {
    id: 'e21',
    projectId: 'Helios Corporation',
    text: 'Project kickoff meeting held',
    createdAt: 1691884800000,
    type: 'Event',
    message: 'Project kickoff meeting held',
  },
  {
    id: 'e22',
    projectId: 'Quantum Innovations',
    text: 'Major milestone achieved',
    createdAt: 1694563200000,
    type: 'Event',
    message: 'Major milestone achieved',
  },
  {
    id: 'e23',
    projectId: 'Aurora Systems',
    text: 'Client presentation scheduled',
    createdAt: 1697241600000,
    type: 'Event',
    message: 'Client presentation scheduled',
  },
  {
    id: 'e24',
    projectId: 'Nebula Solutions',
    text: 'Team restructuring announced',
    createdAt: 1699920000000,
    type: 'Event',
    message: 'Team restructuring announced',
  },
  {
    id: 'e25',
    projectId: 'Titan Enterprises',
    text: 'Budget review completed',
    createdAt: 1702598400000,
    type: 'Event',
    message: 'Budget review completed',
  },
  {
    id: 'e26',
    projectId: 'Vertex Industries',
    text: 'New team member onboarded',
    createdAt: 1673740800000,
    type: 'Event',
    message: 'New team member onboarded',
  },
  {
    id: 'e27',
    projectId: 'Orion Technologies',
    text: 'Project deadline extended',
    createdAt: 1676419200000,
    type: 'Event',
    message: 'Project deadline extended',
  },
  {
    id: 'e28',
    projectId: 'Pulse Innovations',
    text: 'Unexpected issue encountered',
    createdAt: 1679097600000,
    type: 'Event',
    message: 'Unexpected issue encountered',
  },
  {
    id: 'e29',
    projectId: 'Sigma Dynamics',
    text: 'Critical bug resolved',
    createdAt: 1681776000000,
    type: 'Event',
    message: 'Critical bug resolved',
  },
  {
    id: 'e30',
    projectId: 'Eclipse Systems',
    text: 'Client feedback received',
    createdAt: 1684454400000,
    type: 'Event',
    message: 'Client feedback received',
  },
  {
    id: 'e31',
    projectId: 'Quantum Dynamics',
    text: 'Project kickoff meeting held',
    createdAt: 1687132800000,
    type: 'Event',
    message: 'Project kickoff meeting held',
  },
  {
    id: 'e32',
    projectId: 'Nexus Technologies',
    text: 'Major milestone achieved',
    createdAt: 1689811200000,
    type: 'Event',
    message: 'Major milestone achieved',
  },
  {
    id: 'e33',
    projectId: 'Emerald Innovations',
    text: 'Client presentation scheduled',
    createdAt: 1692489600000,
    type: 'Event',
    message: 'Client presentation scheduled',
  },
  {
    id: 'e34',
    projectId: 'Stellar Systems',
    text: 'Team restructuring announced',
    createdAt: 1695168000000,
    type: 'Event',
    message: 'Team restructuring announced',
  },
  {
    id: 'e35',
    projectId: 'Apex Solutions',
    text: 'Budget review completed',
    createdAt: 1697846400000,
    type: 'Event',
    message: 'Budget review completed',
  },
  {
    id: 'e36',
    projectId: 'Fusion Enterprises',
    text: 'New team member onboarded',
    createdAt: 1700524800000,
    type: 'Event',
    message: 'New team member onboarded',
  },
  {
    id: 'e37',
    projectId: 'Zenith Corporation',
    text: 'Project deadline extended',
    createdAt: 1703203200000,
    type: 'Event',
    message: 'Project deadline extended',
  },
  {
    id: 'e38',
    projectId: 'Prism Industries',
    text: 'Unexpected issue encountered',
    createdAt: 1674345600000,
    type: 'Event',
    message: 'Unexpected issue encountered',
  },
  {
    id: 'e39',
    projectId: 'Velocity Ventures',
    text: 'Critical bug resolved',
    createdAt: 1677024000000,
    type: 'Event',
    message: 'Critical bug resolved',
  },
  {
    id: 'e40',
    projectId: 'Oasis Innovations',
    text: 'Client feedback received',
    createdAt: 1679702400000,
    type: 'Event',
    message: 'Client feedback received',
  },
  {
    id: 'e41',
    projectId: 'Horizon Dynamics',
    text: 'Project kickoff meeting held',
    createdAt: 1682380800000,
    type: 'Event',
    message: 'Project kickoff meeting held',
  },
  {
    id: 'e42',
    projectId: 'Catalyst Systems',
    text: 'Major milestone achieved',
    createdAt: 1685059200000,
    type: 'Event',
    message: 'Major milestone achieved',
  },
  {
    id: 'e43',
    projectId: 'Nova Technologies',
    text: 'Client presentation scheduled',
    createdAt: 1687737600000,
    type: 'Event',
    message: 'Client presentation scheduled',
  },
  {
    id: 'e44',
    projectId: 'Aegis Solutions',
    text: 'Team restructuring announced',
    createdAt: 1690416000000,
    type: 'Event',
    message: 'Team restructuring announced',
  },
  {
    id: 'e45',
    projectId: 'Phoenix Enterprises',
    text: 'Budget review completed',
    createdAt: 1693094400000,
    type: 'Event',
    message: 'Budget review completed',
  },
  {
    id: 'e46',
    projectId: 'Pinnacle Industries',
    text: 'New team member onboarded',
    createdAt: 1695772800000,
    type: 'Event',
    message: 'New team member onboarded',
  },
  {
    id: 'e47',
    projectId: 'Vortex Innovations',
    text: 'Project deadline extended',
    createdAt: 1698451200000,
    type: 'Event',
    message: 'Project deadline extended',
  },
  {
    id: 'e48',
    projectId: 'Meridian Systems',
    text: 'Unexpected issue encountered',
    createdAt: 1701129600000,
    type: 'Event',
    message: 'Unexpected issue encountered',
  },
  {
    id: 'e49',
    projectId: 'Cyber Dynamics',
    text: 'Critical bug resolved',
    createdAt: 1703808000000,
    type: 'Event',
    message: 'Critical bug resolved',
  },
  {
    id: 'e50',
    projectId: 'Elysium Technologies',
    text: 'Client feedback received',
    createdAt: 1674950400000,
    type: 'Event',
    message: 'Client feedback received',
  },
  {
    id: 'e51',
    projectId: 'Helios Corporation',
    text: 'Project kickoff meeting held',
    createdAt: 1677628800000,
    type: 'Event',
    message: 'Project kickoff meeting held',
  },
  {
    id: 'e52',
    projectId: 'Quantum Innovations',
    text: 'Major milestone achieved',
    createdAt: 1680307200000,
    type: 'Event',
    message: 'Major milestone achieved',
  },
  {
    id: 'e53',
    projectId: 'Aurora Systems',
    text: 'Client presentation scheduled',
    createdAt: 1682985600000,
    type: 'Event',
    message: 'Client presentation scheduled',
  },
  {
    id: 'e54',
    projectId: 'Nebula Solutions',
    text: 'Team restructuring announced',
    createdAt: 1685664000000,
    type: 'Event',
    message: 'Team restructuring announced',
  },
  {
    id: 'e55',
    projectId: 'Titan Enterprises',
    text: 'Budget review completed',
    createdAt: 1688342400000,
    type: 'Event',
    message: 'Budget review completed',
  },
  {
    id: 'e56',
    projectId: 'Vertex Industries',
    text: 'New team member onboarded',
    createdAt: 1691020800000,
    type: 'Event',
    message: 'New team member onboarded',
  },
  {
    id: 'e57',
    projectId: 'Orion Technologies',
    text: 'Project deadline extended',
    createdAt: 1693699200000,
    type: 'Event',
    message: 'Project deadline extended',
  },
  {
    id: 'n1',
    projectId: 'Quantum Dynamics',
    text: 'Remember to follow up with the client about project requirements',
    createdAt: 1672531200000,
    type: 'Note',
  },
  {
    id: 'n2',
    projectId: 'Nexus Technologies',
    text: 'Schedule team meeting to discuss progress on feature X',
    createdAt: 1675209600000,
    type: 'Note',
  },
  {
    id: 'n3',
    projectId: 'Emerald Innovations',
    text: 'Need to update project documentation before next review',
    createdAt: 1677888000000,
    type: 'Note',
  },
  {
    id: 'n4',
    projectId: 'Stellar Systems',
    text: 'Investigate performance issues reported by QA team',
    createdAt: 1680566400000,
    type: 'Note',
  },
  {
    id: 'n5',
    projectId: 'Apex Solutions',
    text: 'Prepare presentation for stakeholder meeting next week',
    createdAt: 1683158400000,
    type: 'Note',
  },
  {
    id: 'n6',
    projectId: 'Fusion Enterprises',
    text: 'Review and approve new design mockups',
    createdAt: 1685836800000,
    type: 'Note',
  },
  {
    id: 'n7',
    projectId: 'Zenith Corporation',
    text: 'Follow up on pending approvals for budget increase',
    createdAt: 1688515200000,
    type: 'Note',
  },
  {
    id: 'n8',
    projectId: 'Prism Industries',
    text: 'Organize code review session for new module',
    createdAt: 1691193600000,
    type: 'Note',
  },
  {
    id: 'n9',
    projectId: 'Velocity Ventures',
    text: 'Discuss potential risks and mitigation strategies with team',
    createdAt: 1693872000000,
    type: 'Note',
  },
  {
    id: 'n10',
    projectId: 'Oasis Innovations',
    text: 'Prepare monthly progress report for management',
    createdAt: 1696550400000,
    type: 'Note',
  },
  {
    id: 'n11',
    projectId: 'Horizon Dynamics',
    text: 'Research new technologies for upcoming project phase',
    createdAt: 1699228800000,
    type: 'Note',
  },
  {
    id: 'n12',
    projectId: 'Catalyst Systems',
    text: 'Schedule training session for new team members',
    createdAt: 1701820800000,
    type: 'Note',
  },
  {
    id: 'n13',
    projectId: 'Nova Technologies',
    text: 'Review and update project timeline',
    createdAt: 1704499200000,
    type: 'Note',
  },
  {
    id: 'n14',
    projectId: 'Aegis Solutions',
    text: 'Coordinate with marketing team for product launch',
    createdAt: 1673136000000,
    type: 'Note',
  },
  {
    id: 'n15',
    projectId: 'Phoenix Enterprises',
    text: 'Analyze user feedback from beta testing',
    createdAt: 1675814400000,
    type: 'Note',
  },
  {
    id: 'n16',
    projectId: 'Pinnacle Industries',
    text: 'Prepare agenda for next sprint planning meeting',
    createdAt: 1678492800000,
    type: 'Note',
  },
  {
    id: 'n17',
    projectId: 'Vortex Innovations',
    text: 'Follow up on hardware procurement for dev environment',
    createdAt: 1681171200000,
    type: 'Note',
  },
  {
    id: 'n18',
    projectId: 'Meridian Systems',
    text: 'Review and update project risk register',
    createdAt: 1683849600000,
    type: 'Note',
  },
  {
    id: 'n19',
    projectId: 'Cyber Dynamics',
    text: 'Schedule security audit for new features',
    createdAt: 1686528000000,
    type: 'Note',
  },
  {
    id: 'n20',
    projectId: 'Elysium Technologies',
    text: 'Prepare demo for upcoming client meeting',
    createdAt: 1689206400000,
    type: 'Note',
  },
  {
    id: 'n21',
    projectId: 'Helios Corporation',
    text: 'Review and approve expense reports',
    createdAt: 1691884800000,
    type: 'Note',
  },
  {
    id: 'n22',
    projectId: 'Quantum Innovations',
    text: 'Follow up on outstanding bugs from last release',
    createdAt: 1694563200000,
    type: 'Note',
  },
  {
    id: 'n23',
    projectId: 'Aurora Systems',
    text: 'Schedule retrospective meeting for completed sprint',
    createdAt: 1697241600000,
    type: 'Note',
  },
  {
    id: 'n24',
    projectId: 'Nebula Solutions',
    text: 'Update project status dashboard for stakeholders',
    createdAt: 1699920000000,
    type: 'Note',
  },
  {
    id: 'n25',
    projectId: 'Titan Enterprises',
    text: 'Research competitive products for market analysis',
    createdAt: 1702598400000,
    type: 'Note',
  },
  {
    id: 'n26',
    projectId: 'Vertex Industries',
    text: 'Prepare onboarding documents for new team member',
    createdAt: 1673740800000,
    type: 'Note',
  },
  {
    id: 'n27',
    projectId: 'Orion Technologies',
    text: 'Review and update API documentation',
    createdAt: 1676419200000,
    type: 'Note',
  },
  {
    id: 'n28',
    projectId: 'Pulse Innovations',
    text: 'Schedule meeting with UX team to discuss user feedback',
    createdAt: 1679097600000,
    type: 'Note',
  },
  {
    id: 'n29',
    projectId: 'Sigma Dynamics',
    text: 'Prepare quarterly review presentation',
    createdAt: 1681776000000,
    type: 'Note',
  },
  {
    id: 'n30',
    projectId: 'Eclipse Systems',
    text: 'Follow up on pending legal approvals for new feature',
    createdAt: 1684454400000,
    type: 'Note',
  },
  {
    id: 'n31',
    projectId: 'Quantum Dynamics',
    text: 'Review and update project cost estimates',
    createdAt: 1687132800000,
    type: 'Note',
  },
  {
    id: 'n32',
    projectId: 'Nexus Technologies',
    text: 'Schedule team building activity for next month',
    createdAt: 1689811200000,
    type: 'Note',
  },
  {
    id: 'n33',
    projectId: 'Emerald Innovations',
    text: 'Investigate alternative solutions for performance bottleneck',
    createdAt: 1692489600000,
    type: 'Note',
  },
  {
    id: 'n34',
    projectId: 'Stellar Systems',
    text: 'Prepare project closure report for completed phase',
    createdAt: 1695168000000,
    type: 'Note',
  },
  {
    id: 'n35',
    projectId: 'Apex Solutions',
    text: 'Schedule knowledge transfer sessions with departing team member',
    createdAt: 1697846400000,
    type: 'Note',
  },
  {
    id: 'n36',
    projectId: 'Fusion Enterprises',
    text: 'Review and update test cases for regression testing',
    createdAt: 1700524800000,
    type: 'Note',
  },
  {
    id: 'n37',
    projectId: 'Zenith Corporation',
    text: 'Prepare agenda for steering committee meeting',
    createdAt: 1703203200000,
    type: 'Note',
  },
  {
    id: 'n38',
    projectId: 'Prism Industries',
    text: "Follow up on client's change requests",
    createdAt: 1674345600000,
    type: 'Note',
  },
  {
    id: 'n39',
    projectId: 'Velocity Ventures',
    text: 'Review and approve vendor proposals',
    createdAt: 1677024000000,
    type: 'Note',
  },
  {
    id: 'n40',
    projectId: 'Oasis Innovations',
    text: 'Schedule performance reviews for team members',
    createdAt: 1679702400000,
    type: 'Note',
  },
  {
    id: 'n41',
    projectId: 'Horizon Dynamics',
    text: 'Prepare project handover documentation',
    createdAt: 1682380800000,
    type: 'Note',
  },
  {
    id: 'n42',
    projectId: 'Catalyst Systems',
    text: 'Review and update project communication plan',
    createdAt: 1685059200000,
    type: 'Note',
  },
  {
    id: 'n43',
    projectId: 'Nova Technologies',
    text: 'Investigate options for cloud migration',
    createdAt: 1687737600000,
    type: 'Note',
  },
  {
    id: 'n44',
    projectId: 'Aegis Solutions',
    text: 'Prepare materials for upcoming client workshop',
    createdAt: 1690416000000,
    type: 'Note',
  },
  {
    id: 'n45',
    projectId: 'Phoenix Enterprises',
    text: 'Schedule code freeze for upcoming release',
    createdAt: 1693094400000,
    type: 'Note',
  },
  {
    id: 'n46',
    projectId: 'Pinnacle Industries',
    text: 'Review and update project resource allocation',
    createdAt: 1695772800000,
    type: 'Note',
  },
  {
    id: 'n47',
    projectId: 'Vortex Innovations',
    text: 'Prepare release notes for next version',
    createdAt: 1698451200000,
    type: 'Note',
  },
  {
    id: 'n48',
    projectId: 'Meridian Systems',
    text: 'Schedule user acceptance testing sessions',
    createdAt: 1701129600000,
    type: 'Note',
  },
  {
    id: 'n49',
    projectId: 'Cyber Dynamics',
    text: 'Review and update project KPIs',
    createdAt: 1703808000000,
    type: 'Note',
  },
  {
    id: 'n50',
    projectId: 'Elysium Technologies',
    text: 'Prepare end-of-year project summary for management',
    createdAt: 1674950400000,
    type: 'Note',
  },
];
